using CustomerSupport.Application.Interfaces.Authentication;
using CustomerSupport.Application.Models;
using CustomerSupport.Domain.Entities;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;

namespace CustomerSupport.Infrastructure.Authentication
{
    public sealed class JwtTokenService : ITokenService
    {
        // Contains JWT configuration such as signing key,
        // issuer, audience, and token expiration periods.
        private readonly JwtSettings _settings;

        public JwtTokenService(JwtSettings settings)
        {
            _settings = settings;
        }

        public AccessTokenResult CreateAccessToken(User user)
        {
            // Access Tokens should be short-lived.
            // The expiration time is calculated using UTC to avoid timezone issues.
            var expiresAt = DateTime.UtcNow.AddMinutes(_settings.AccessTokenMinutes);

            // Claims represent information about the authenticated user
            // that will be stored inside the JWT Access Token.
            var claims = new List<Claim>
            {
                // Standard JWT subject claim.
                // Identifies the user represented by this token.
                new Claim(JwtRegisteredClaimNames.Sub, user.Id.ToString()),

                // ASP.NET Core commonly uses NameIdentifier
                // to retrieve the authenticated User ID.
                new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),

                // Store the user's display name in the token.
                new Claim(ClaimTypes.Name, $"{user.FirstName} {user.LastName}"),

                // Store the authenticated user's email address.
                new Claim(ClaimTypes.Email, user.Email),

                // Store the user's role so ASP.NET Core can later
                // perform Role-Based Authorization.
                new Claim(ClaimTypes.Role, user.RoleId.ToString()),

                // JTI is a unique identifier for this particular JWT.
                // Each Access Token receives a different value.
                new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString())
            };

            // Convert the configured secret key into a security key
            // that can be used for signing the JWT.
            var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_settings.Key));

            // Define the signing algorithm used to digitally sign the token.
            // The signature allows the API to verify that the token
            // was generated by a trusted server and was not modified.
            var credentials = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);

            // Create the JWT using the configured issuer, audience,
            // user claims, expiration time, and signing credentials.
            var token = new JwtSecurityToken(
                    issuer: _settings.Issuer,
                    audience: _settings.Audience,
                    claims: claims,
                    expires: expiresAt,
                    signingCredentials: credentials);

            // Convert the JwtSecurityToken object into the compact
            // JWT string that can be returned to the client.
            var tokenValue = new JwtSecurityTokenHandler().WriteToken(token);

            // Return both the token and its expiration time
            // to the Application layer.
            return new AccessTokenResult
            {
                Token = tokenValue,
                ExpiresAt = expiresAt
            };
        }

        public RefreshTokenResult CreateRefreshToken()
        {
            // A Refresh Token should be unpredictable and cryptographically secure.
            var randomBytes = RandomNumberGenerator.GetBytes(64);

            // Convert the random bytes into a URL-safe string
            // that can safely be transferred between client and server.
            var token = Base64UrlEncoder.Encode(randomBytes);

            // Refresh Tokens live longer than Access Tokens.
            var expiresAt = DateTime.UtcNow.AddDays(_settings.RefreshTokenDays);

            // The raw Refresh Token will be returned to the client.
            // Later, only its hash will be stored in the database.
            return new RefreshTokenResult
            {
                Token = token,
                ExpiresAt = expiresAt
            };
        }

        public string ComputeRefreshTokenHash(string refreshToken)
        {
            // Convert the raw Refresh Token into bytes before hashing it.
            var bytes = Encoding.UTF8.GetBytes(refreshToken);

            // Hash the Refresh Token using SHA-256.
            // We store the hash instead of storing the raw token
            // so that a database leak does not directly expose usable tokens.
            var hash = SHA256.HashData(bytes);

            // Convert the binary hash into a string suitable
            // for storing and comparing in the database.
            return Convert.ToHexString(hash);
        }
    }
}